trigger: ":bab"
replace: |
             Before: $|$
             After:
             Bridge: outline the steps or actions to bridge the gap.
label: "Before - After - Bridge"
source: https://www.linkedin.com/posts/jeremygrandillon_5-chatgpt-prompt-frameworks-that-make-your-activity-7301956962898837504-NR_i
author: ""